// <auto-generated />
using System;
using ConferenceRooms.Infrastracture.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceRooms.Infrastructure.Migrations
{
    [DbContext(typeof(ConferenceBookingDbContext))]
    [Migration("20260622220856_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall_id");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("HallId", "Start", "End");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Time", "end_time > start_time");

                            t.HasCheckConstraint("CK_Bookings_TotalPrice", "total_price >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.BookingService", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_at_booking");

                    b.HasKey("BookingId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BookingId", "ServiceId");

                    b.ToTable("booking_services", null, t =>
                        {
                            t.HasCheckConstraint("CK_Booking_Services_PriceAtBooking", "price_at_booking >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("halls", null, t =>
                        {
                            t.HasCheckConstraint("CK_Halls_Capacity", "\"capacity\" >= 0");

                            t.HasCheckConstraint("CK_Halls_Cost", "\"cost\" >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.HallService", b =>
                {
                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("HallId", "ServiceId");

                    b.HasIndex("HallId");

                    b.HasIndex("ServiceId");

                    b.ToTable("hall_services", null, t =>
                        {
                            t.HasCheckConstraint("CK_Hall_Service_Price", "\"price\" >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ConferenceRooms.Domain.Entities.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.BookingService", b =>
                {
                    b.HasOne("ConferenceRooms.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceRooms.Domain.Entities.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.HallService", b =>
                {
                    b.HasOne("ConferenceRooms.Domain.Entities.Hall", "Hall")
                        .WithMany("HallServices")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceRooms.Domain.Entities.Service", "Service")
                        .WithMany("HallServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Hall", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("HallServices");
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Service", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("HallServices");
                });
#pragma warning restore 612, 618
        }
    }
}
